logging:
  config: classpath:logback.xml
server:
  port: 8081
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://xxljob.middleware.test.gdapi.net:8090/xxl-job-admin
    executor:
      appname: middleware-test
      ip: ''
      logpath: /Users/tc/Documents/workspace/github/sample-parent/sample-xxljob/xxl-job-2.1/log
      logretentiondays: -1
      port: 9999

# 随机的时间边界
gd:
  random:
    max: 10000
    min: 10